# -*- coding: utf-8 -*-
"""review_summary_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E5qbAPLQOnweAsxJya9dKdtT8eHlIOlm

IBM Granite Model Output
> Add blockquote

> Add blockquote





Notebook ini menjalankan klasifikasi dan summarization berdasarkan review dan transcript meeting, dengan penyesuaian parameter untuk meningkatkan output.
"""

!pip install -q replicate

import replicate
import os

# Token API Replicate
os.environ["REPLICATE_API_TOKEN"] = "r8_ShHqiSSCCABsEJumswMOuecDuGzZNbD12a6g4"

# Data ulasan
customer_reviews = [
    "The battery lasts all day, but the phone gets hot during gaming.",
    "The screen is too dim outdoors, but I love the colors indoors.",
    "This phone is fast, but it keeps crashing when I open certain apps."
]

# Format ulasan jadi teks
reviews_text = "\n".join([f"Review {i+1}: {review}" for i, review in enumerate(customer_reviews)])

# Prompt klasifikasi
classification_prompt = f"""
You are a customer review analysis assistant.

Classify the following smartphone reviews as Positive, Negative, or Mixed.
Then tag relevant categories: battery life, screen quality, or performance.

Respond in this format:
- Sentiment: [Positive/Negative/Mixed]
- Categories: [battery life, screen quality, performance]

{reviews_text}
"""

# Jalankan LLaMA 2
classification_output = replicate.run(
    "meta/llama-2-13b-chat",
    input={
        "prompt": classification_prompt,
        "max_new_tokens": 300,
        "temperature": 0.7,
        "top_k": 50,
        "top_p": 0.9,
        "repetition_penalty": 1.0
    }
)

print("📝 Hasil Klasifikasi:\n")
print("".join(classification_output))

# Transkrip rapat
meeting_transcript = """
The meeting began with a discussion of the Q3 marketing budget. It was decided that 40% of the budget will go to digital ads, 30% to events, and 30% to social media campaigns. The team emphasized the need for influencer partnerships to increase brand visibility and email marketing to boost direct engagement. A pilot program to test new ad formats will launch next month.
Later, the team discussed campaign performance metrics. ROI monitoring will be a top priority, and adjustments will be made based on performance data. The events team raised concerns about resource allocation for trade shows, and it was agreed that $10,000 would be reallocated.
Lastly, the team reviewed new creative concepts. They decided to proceed with Concept B which tested better among focus groups. Deadlines for campaign assets were finalized for July 15.
"""

# Prompt ringkasan
summary_prompt = f"""
Summarize this meeting by focusing on key points, decisions, and action items.

Organize the output like this:
- Key Points:
- Decisions:
- Action Items:

{meeting_transcript}
"""

# Jalankan LLaMA 2
summary_output = replicate.run(
    "meta/llama-2-13b-chat",
    input={
        "prompt": summary_prompt,
        "max_new_tokens": 300,
        "temperature": 0.7,
        "top_k": 50,
        "top_p": 0.9,
        "repetition_penalty": 1.0
    }
)

print("\n📋 Ringkasan Rapat:\n")
print("".join(summary_output))